### ISSUE TITLE
User management

### ISSUE THREAD

**Issue by murrant** [librenms/librenmsv2#78]
Implement user management.

Items needed:
- Check permissions level and handle appropriately
- List users with actions such as edit and delete
- Add users
- Manage user's permissions (to devices, ports, and maybe groups)

**Comment by Rosiak** [comment]
Sorry did not see this issue:
We need to simplify our menu system(Waaaay to many options as for now), heres a suggestion for the user management.

Change it a bit so menu wise it becomes:
Menu>
Settings>
Users>

Instead of:
Menu>
Settings>
Add User>
Remove User>
Edit User>

http://www.jquery-bootgrid.com/Examples#basic-selection Should be used - Also edit/del icons should appear on each line(For each user) for quick changes.

Should also contain a dropdown for bulk actions.

What do you think?

**Comment by murrant** [comment]
I'm currently working on this.

What kind of bulk actions did you have in mind?  I can only think of delete.

**Comment by murrant** [comment]
PR #124
